#!/bin/sh
set -e

goroot="$(go env GOROOT)"
mksys="${goroot}/src/pkg/syscall/mksyscall.pl"
if [ ! -f "$mksys" ]; then
    mksys="${goroot}/src/syscall/mksyscall.pl"
fi

if [ ! -f "$mksys" ]; then
    echo "mksyscall.pl not found under ${goroot}" >&2
    exit 1
fi

fix() {
    sed 's,^package syscall$,&x\nimport "syscall",' \
	| gofmt -r='BytePtrFromString -> syscall.BytePtrFromString' \
	| gofmt -r='Syscall6 -> syscall.Syscall6' \
	| gofmt -r='Syscall -> syscall.Syscall' \
	| gofmt -r='errnoErr(a) -> syscall.Errno(a)' \
	| gofmt -r='SYS_GETXATTR -> syscall.SYS_GETXATTR' \
	| gofmt -r='SYS_LISTXATTR -> syscall.SYS_LISTXATTR' \
	| gofmt -r='SYS_SETXATTR -> syscall.SYS_SETXATTR' \
	| gofmt -r='SYS_REMOVEXATTR -> syscall.SYS_REMOVEXATTR' \
	| gofmt -r='SYS_MSYNC -> syscall.SYS_MSYNC' \
	| sed '/^\/\/go:build[[:space:]]*$/d'
}

cd "$(dirname "$0")"

perl "$mksys" xattr_darwin.go \
    | fix \
    >xattr_darwin_syscall.go

perl "$mksys" msync.go \
    | fix \
    >msync_syscall.go
